### ISSUE TITLE
成績画面の表示の仕組み

### ISSUE THREAD

**Issue by takamee** [kawasymantec/dansharies#14]
成績画面は作成したが、それを表示する仕組みがない
（メニューか、画面遷移か）

**Comment by kawasymantec** [comment]
挑戦中画面から遷移できるように挑戦中の画面にボタンを用意するのはどうでしょう？
もともとの画面案では挑戦中画面にユーザ名が表示されていたので、ユーザ名を表示するようにして
ユーザ名をタップすると成績画面がポップアップする。

**Comment by takamee** [comment]
なるほど。ちょっとやってみます。
無理なら申請しますので、よろしくお願いします。

**Comment by takamee** [comment]
名前ボタンを入れると少し画面が見にくくなりそうなため、以下を考えましたが、どうでしょうか？
（今は画像上に名前を重ねられないため、アバターよりも上部分にどんと名前が載る）

● ツールバーの左側に、ヒト型のアイコンを置き、それをクリックするとアバター画面になる。これなら、どの画面でも画面を崩さずに表示できる。
●アバター画面では、上記アイコンが戻るアイコンに変わり、元のページに戻れる。

ここで質問なのですが、
◆上記をすべてのツールバーに入れようとすると、すべてのjsとhtmlを書き換える必要があるのでしょうか？
◆ ～Ctrl as ctrl のよこに、app.js as app とかしてincludeして、app.jsにまとめてかけたりします？
(それでも、すべてもhtmlの修整が必要そうですが)

それとは別に、ツールバーにユーザ名を表示させてはと思ったのですが、
ユーザ名ってDBアクセスしないと取得できませんか？
ログイン中の currentUser も mBaaS から取得しているみたいですが…

**Comment by takamee** [comment]
●現在の機能
　・挑戦中画面からアバター画面に遷移できる
　・上記の場合に限り、アバター画面から元の画面に戻ることができる

★問題★
　・ミッションが終わった後などに、アバター画面が通常処理で表示されている場合、戻る機能が働かない
　→ 「戻る」の代わりに「ミッション」ボタンなどにして、
       押したら「ミッション挑戦中」「ミッション開始画面」「本日のミッションはありません」などの、
       いずれかが表示されるようにするとか？

  → 別案として、「戻る付きアバター画面」と「通常アバター画面」の2つを用意するとか？
      そもそも、「通常アバター画面」から、どうやってミッションに行くのかという問題があるのかも…
