### ISSUE TITLE
画面遷移

### ISSUE THREAD

**Issue by kawasymantec** [kawasymantec/dansharies#22]
画面遷移をちょっと整理

**Comment by kawasymantec** [comment]
ログイン後の画面をタブで切りかえる。
ＴＡＢ－１.....ミッション画面
ＴＡＢ－２.....アバタ―画面
ミッションなしで従来は、アバタ―を表示していたが、とりあえずミッションなし画面にしておく。
前回チャレンジサマリー画面が完成次第、差し替える。

**Comment by kawasymantec** [comment]
タブ切り替えのためには、現在の画面遷移の仕組みを変えないとだめなことが判明
replacePageをしようするとタブが無効化されてしまう。

**Comment by takamee** [comment]
ログイン→アバター→ミッション（ミッションなし、ミッション選択→…→ミッション中→…ミッション終了）
　　　　　　　　↑________________________|_______________|___________________|_ _ _ _ _ _ _ _ _|※

この遷移になる版の作成を検討します（前作ったやつがブランチ消滅しているけど再利用できそうなので）
この修正は↑を解決した際には捨ててもらって構いませんので。

[memo]
各ページのツールバー左上に、myNavigator.replacePage('status.html');のような形でアイコンを追加。
アバター画面に行くものは「人型、person」アイコンを使い、
ミッション画面に行くものは「クリップボード、clipboard」アイコンを使っている。

※部分はさわっていません。もともと、そうなっていた気がするので何もしていません。

**Comment by kawasymantec** [comment]
修正ありがとうございます。loadPageを使えばいけそうな感じなので一度トライしてみます。ダメだったら修正マージさせてもらいます！

**Comment by takamee** [comment]
了解です。

話がずれますが、ミッション無しの画面について、まだ画像などなければ、以下のフリー素材などを使うと、画面がさみしくなくなるかなと思いました。

http://business-icon.com/05-analysis/088-analysis.html
で、看板に「次のミッションまでx日」と文字をかぶせたり、

http://icon-rainbow.com/%E3%81%8A%E5%BA%97%E3%81%AE%E7%9C%8B%E6%9D%BF%E3%82%AF%E3%83%AD%E3%83%BC%E3%82%BA%E3%81%AE%E7%84%A1%E6%96%99%E3%82%A2%E3%82%A4%E3%82%B3%E3%83%B3%E7%B4%A0%E6%9D%90-2/
で、ミッション無し（次は何日後）の文字に加えて、これを表示
