### ISSUE TITLE
アバタ―が反映されない

### ISSUE THREAD

**Issue by kawasymantec** [kawasymantec/dansharies#27]
挑戦中などの画面のアバタ―が成長してない。。。

**Comment by takamee** [comment]
アバターの成長を、他の画面に反映させる場合、
user情報に「Lv」(アバターのレベル)「B-Lv」(背景のレベル)の情報を持たせる必要があるかもしれません。

現状では、常にどの画面でも、challengerを参照して、達成度を計算→レベル算出→適切なアバターを表示
という流れが必要になるため

**Comment by takamee** [comment]
[memo]
アバターが反映されない画面と、用意するべき画像
○：アバターが反映されるようになったもの

○挑戦中画面（challenge.png）　　　　　　　　　　→ 通常アバター、「他の人」の背景
○確認画面（input_result.png）　　　　　　　　　　→ 片手アバター、炎の背景１
○達成画面（complete.png）　　　　　　　　　　　 → 両手アバター、拍手背景
○失敗画面（failure.png）　　　　　　　　　　　　　 → ×目アバター、失敗背景
△次こそは画面（retry.png）：諦めた場合？　　 → 片手アバター、炎の背景２
・応援画面：顔部分を表示するのであれば？　→ 

※　×目アバターは、今はLv1がそもそも×目。他は通常目。
※　炎の背景１、２は、背景に書かれた「メッセージ」が違う。
※　失敗背景は、今のLv1背景と同じものを利用している。

※失敗画面＝次こそは画面と判断して、failure.htmlに「次こそは」の画像を表示中

[status]
・すべてのページでLvを取得できるように、challneger.js に関数を追加
・それに伴って、取得した達成回数から、Lvを計算する処理を、challengerの中の関数に設定
  （なお、アバター・背景のLv：challenger、メダルの色：statusCtrlで決定している）

question]
・次こそは画面と、失敗画面って、両方使われていますか？どこで使われているのか分からなく…

**Comment by takamee** [comment]
現在のアバター関連の画像を、いかに置きました。

06_だんしゃりーず\プログラム用画像ファイル\

画像.pptx で作成して、pngで保存していることを繰り返しています。

**Comment by takamee** [comment]
成功画面の、「やったー」の立体文字ですが、作業中に消えてしまいました。
必要ならば、誰かもともとのソースがある方がいましたら、もどしておいてもらえますか？

**Comment by takamee** [comment]
めも

ミッション完了の結果、challengerにsuccesssが入るのがいつのタイミングかにもよるが、
 現在、「毎回DBにアクセスしてLvを計算」 している都合上、
レベルアップした場合、何のエフェクトもなしに、画面遷移の途中で、アバターが変化する。

「Lvアップ時のエフェクト」のissueに関連する話なので注意。

なお、そもそも「毎回DBにアクセスしてLvを計算」していることに問題があるので、
そこを修整すれば、なんとかなりそう。

**Comment by kawasymantec** [comment]
取り込み済み
