### ISSUE TITLE
励ましコメント表示

### ISSUE THREAD

**Issue by sumioka** [kawasymantec/dansharies#3]
・励ましコメント表示
　励まし機能によって登録された励ましコメントを表示する機能が無い
　励まされ機能で表示するか、ミッションチャレンジ中の画面に表示するのが良いかと思います。

**Comment by tttaaaa** [comment]
すいません．

javascriptわからんマンなので，質問させてください．

challengeCtrl.jsの62行目

```
challenger.ChallengeGetCheer(challenger.currentMission.objectId,function(cheer)
console.log("応援取得:" + cheer.username);
console.log("応援取得:" + cheer.message);
```

でcheerに応援メッセージ等を取ってきてると思うのですが，
この値を関数の外で使うためにはどうすればいいのでしょう？

**Comment by kawasymantec** [comment]
GetChallengerCount あたりの使い方をみてもらえるとわかりますかね。
ここでは、チャレンジ中の参加者を画面に反映させてます。activeChallenger とかtotalChallenger 。

わかりずらいのは $timeoutで一回ラッピングしているところだとおもいます。
これはAngularJSをつかってコントローラが保持している値が変化した際に自動でView側（HTML）の表示を変化させるために小細工をしてます。
コントローラクラスの値をモデル側の処理が終了したタイミング（NDMBからデータを取得できたタイミングですね）で、更新するのですが、このタイミングで更新すると、AngularJSが値の変化に気づけないので
$timeoutをつかって、AngularJSが値の変化に気づけるようにしています。

ng-clickでコントローラの関数を呼んだ処理の中であれば、処理が終了した時点でViewに自動で反映されるのですが、非同期の場合は反映させるタイミングがなくなってしまうので、こうして反映させてます。

**Comment by tttaaaa** [comment]
コメントありがとうございました。
関数の外にログを書いてみても反映されないので、焦りましたが、画面には無事表示されました。

プルリクエスト＋マージ済です。
マージ初めてだったので、やり方が間違っているかもしれません。

誰も応援メッセージを発していない場合にどうするかはTBDです。(管理者から初期にメッセージを作る？今回は諦める？)

**Comment by sumioka** [comment]
デフォルトは、竹川さんの絵とメッセージを出す

**Comment by takamee** [comment]
Game関連のものであっても、画像が、お茶のクーポンが出てくる。

**Comment by kawasymantec** [comment]
とりあえず、お茶クーポンだけは出ないように修正してます。
（固定画像になった）
