### ISSUE TITLE
レベルアップ、および、アバター更新エフェクト

### ISSUE THREAD

**Issue by sumioka** [kawasymantec/dansharies#32]
ミッション完了時にレベルアップエフェクトを追加する

**Comment by takamee** [comment]
ミッション完了の結果、challengerにsuccesssが入るのがいつのタイミングかにもよるが、
現在、「毎回DBにアクセスしてLvを計算」 している都合上、
レベルアップした場合、何のエフェクトもなしに、画面遷移の途中で、アバターが変化する。

challengerにsuccessを入れるタイミングが「resultEntryCtrl.html 」で「成功(達成)ボタンをクリックした後」
のようなので、そのタイミングで/直後の「success.html」で、
エフェクトを入れるのが、ソースコードの改変が一番少ないと思う。

それ以降でエフェクトを出す場合、「ミッション開始時のアバターのLv」を保持しておく必要が出てくるかも。
で、「エフェクト後」に、新しくなったアバターのLvを表示する必要がありそう。
