### ISSUE TITLE
成績画面の準備

### ISSUE THREAD

**Issue by sumioka** [kawasymantec/dansharies#6]
・成績画面の準備
　チャレンジした成果を表示する画面を追加する
　トロフィー、バッジ的なものやアバタ―の表示など

**Comment by kawasymantec** [comment]
すいません、ここにコメントします。
curentMissionの件ですが、ミッションに参加履歴がなくてもミッション参加待ち状態であれば、currentMissionにミッションが格納されてます。（ミッション参加待ちの画面を出すために格納）
あと,データが取得できない件ですが、取得はできているようです。ただこの部分は非同期実行されるので、いかのデバッグのやりかただと実行されていないようにみえています
これは、全般的なのですが、NCMBからデータを取得する場合、すべて通信を伴うため、非同期で実行されます。
なので、コントローラ側としては取得したデータを使う場合、かならず関数を渡して処理終了時に呼び出してもらう必要があります。すべてのchallengerクラスのメソッドに引数として成功時と失敗時の関数渡しているのはそのためです。

すいません、説明が下手なのでわからなければまた質問してください。

**Comment by takamee** [comment]
コメントありがとうございます。
関数を渡すだけでは、処理されずに進んでしまいました。
が、challengeCtrlを参考に、
関数の中のtimeout内で処理を行うようにした関数を渡すことで、処理されているように見えます。
(一回値が入ってない画面が表示されて、次に数値がある画面が出ている？)
timeout関数が分かっていませんが、100ms後にfunctionを実行してくると思って作成しています。

ということで、一応完成しました。
mBaaSから値を取得して、アバター・背景・メダルの色や値を変えてくれます。
（最後のコミットでデバッグ用の変更をコミットしたために、表示コメントがおかしいように見えますが）

一応、以下を確認しています。
・ミッション１回成功、１回失敗のユーザ→達成度１と表示
・ミッション未着手のユーザ→達成度0と表示

**Comment by takamee** [comment]
●作成
ログインした状態でにアクセスすることで、そのユーザの成績と、成績に応じたアバター、背景、メダルを表示する機能（status.html, statusCtrl.js, challenge.js）

●残課題（別issueにすべき）
成績表示画面を表示する方法
項目別の成績表示 (new)

(memo) missionに項目に関する情報が無いため、現在は項目別の成績は計算できません。便宜上、すべて飲食系扱いです。

**Comment by kodakat** [comment]
西島さん、クローズする前にプルリクエストしないと。

**Comment by takamee** [comment]
なるほど！　リオープンしました。
ついでにデバッグ用の表示機能などは消しておきます。

**Comment by takamee** [comment]
プルリクエストしました。
一応、マスターとの比較では干渉は無いとのコメントでした。

作成したけど使わなかった画像ファイルもアップロードされようとしているのですが（アバターと背景がセットのもの）、これは、私のブランチで削除してから、コミット、プッシュ、プルリクしないと消せないのでしょうか？

**Comment by kodakat** [comment]
不要な画像は再度プッシュして消してください。
再プルリクエストは不要です（確か）。

**Comment by takamee** [comment]
ありがとうございます。アバター関連の画像を削除してcommit/pushしました。
