### ISSUE TITLE
ミッション追加画面の作成

### ISSUE THREAD

**Issue by sumioka** [kawasymantec/dansharies#9]
アプリじゃなくても可
URL知っている人だけが行きつける

**Comment by takamee** [comment]
issues#16に書きましたが、ミッションに項目（種別）の属性がつけれるとうれしいです。
具体的には、遊び系、飲食系、の2分類があることを想定して、成績表示画面を作っています。
（特にタグとかは無いのですが）

全体での重要度は低めですが・・・

**Comment by sumioka** [comment]
#40
